### ISSUE TITLE
Bump cort.el version because of org-generate

### ISSUE THREAD

**Issue by wigust** [conao3/cort.el#106]
Hi,

org-generate tests suite requires new functions which are not available at the latest cort.el release.

Could you bump the version, please?

Thanks,
Oleg.

**Comment by conao3** [comment]
Sure, tagged v7.1.0. But the recent 2 feature PR is not included.
If the functions you want are included in the 2 feature PR, I suggest depending on v9999 of cort.
This makes package.el download HEAD cort from MELPA archive (v20200606.635 for now ([MELPA](https://melpa.org/#/cort)))

**Comment by conao3** [comment]
Oops, my [org-generate](https://github.com/conao3/org-generate.el)?
Thanks, for the notification, but do you have any issues with that?

**Comment by wigust** [comment]
> Oops, my [org-generate](https://github.com/conao3/org-generate.el)?
> Thanks, for the notification, but do you have any issues with that?

Yes, I cannot build org-generate.el with tag v1.0.0 and v7.1.0:
```
starting phase `check'
Loading /gnu/store/269ak1p52d93fcha6i3m3xk3brr0glp6-emacs-mustache-0.23/share/emacs/site-lisp/mustache-render.el (source)...
Loading /gnu/store/269ak1p52d93fcha6i3m3xk3brr0glp6-emacs-mustache-0.23/share/emacs/site-lisp/mustache-lex.el (source)...
Loading /gnu/store/269ak1p52d93fcha6i3m3xk3brr0glp6-emacs-mustache-0.23/share/emacs/site-lisp/mustache-parse.el (source)...
Eager macro-expansion failure: (wrong-type-argument sequencep :equal)
Eager macro-expansion failure: (wrong-type-argument sequencep :equal)
Wrong type argument: sequencep, :equal
command "emacs" "--batch" "--quick" "--directory=." "--load=org-generate-tests.el" "--funcall=cort-test-run" failed with status 255
```

I succeeded to build org-generate.el with 495c3972b92b57a0cb5dd65ce5de9d3c6b8b6509 of cort.el.  But this hash is not tagged currently.

I prefer not to use v9999, because I want to package org-generate.el for [Guix](https://guix.gnu.org/) package manager. It requires to provide him a sha256 sum of a source, which will change v9999 as far as I understand.  I could use 495c3972b92b57a0cb5dd65ce5de9d3c6b8b6509, but I think org-generate.el and cort.el should be build with their tags (aka releases). WDYT?

**Comment by conao3** [comment]
I don't use Guix, but I have much expectations for it as a package manager.

However, I raise the version by 0.0.1 per PR, do tag releases every 0.1, and raise the version by 1 when I make incompatible changes, and this will not change.
This time, this is due to `org-generate`'s use of advanced features not included in the tag release, which is not a reason to tag by `cort` project.
If Guix allows you to specify the tag with a hash, please use that feature to solve the problem.

**Comment by wigust** [comment]
>  If Guix allows you to specify the tag with a hash, please use that feature to solve the problem.

Sure, it does.  I will.  Thank you for fast response!

Closing the issue.
